### ISSUE TITLE
Sync player ships

### ISSUE THREAD

**Issue by Raicuparta** [Raicuparta/quantum-space-buddies#20]
Two ways we can go about this.

Easy way would be just showing a dummy ship model around the player if they're currently piloting a ship. Could be easily achieved by just having an `isPilotingShip` flag, that is broadcast with a bool message.

Harder way is to actually sync each ship's position separately from the players. Would need to replicate the behavior already implemented with the player models, including all the sector stuff. Be cool if we could refactor it so that the same behavior is used for syncing player positions, ship positions, and any other moving objects we might want to sync. But each synced object will mean an extra load on the server...

**Comment by amazingalek** [comment]
Solved by @Raicuparta 👍
