### ISSUE TITLE
Reset ship on respawn if it gets destroyed

### ISSUE THREAD

**Issue by Raicuparta** [Raicuparta/quantum-space-buddies#40]
Right now if the ship is destroyed, it will respawn at the start, but still be destroyed.

**Comment by amazingalek** [comment]
Suggestion: we prevent total ship destruction. We're already preventing proper death so why not? :)

**Comment by Raicuparta** [comment]
> Suggestion: we prevent total ship destruction. We're already preventing proper death so why not? :)

Would also remove (or postpone) the need to sync each section of the ship individually. So that would be cool.
