### ISSUE TITLE
Prevent time from stopping while pause menu is open

### ISSUE THREAD

**Issue by Raicuparta** [Raicuparta/quantum-space-buddies#7]
To avoid de-syncing, time scale needs to stay always at one. Will be useful even if we eventually sync everything manually instead of depending on the simultaneous start of all sessions.

**Comment by amazingalek** [comment]
How about manual dozing/meditation? Disable?

**Comment by Raicuparta** [comment]
> How about manual dozing/meditation? Disable?

Should probably completely disable that, yeah
