### ISSUE TITLE
Make fast forward speed proportional to time difference between client and server

### ISSUE THREAD

**Issue by Raicuparta** [Raicuparta/quantum-space-buddies#72]
Right now the speed is a constant 10x, which can still take a while to catch up. If it's constant and too fast, the player can easily overshoot the target time, and will have to pause afterwards. So making it dynamic is better: the bigger the difference, the faster it gets. As the gap becomes smaller, the fastforward speed becomes smaller.

**Comment by amazingalek** [comment]
👍 how about using Mathf.SmoothDamp for calculating the  "catch up" timescale? https://docs.unity3d.com/ScriptReference/Mathf.SmoothDamp.html

**Comment by Raicuparta** [comment]
@amazingalek wouldn't that be the opposite? Making it start slow and end fast? It should start fast and end slow instead.

**Comment by amazingalek** [comment]
Both, it starts slow, then goes fast, then slows down again. Like an elevator :P 
It'll look fancier but will take a bit more time to reach the target. We might just want the "second half" of it, as you suggest.

**Comment by Raicuparta** [comment]
@amazingalek I guess if we start the velocity at half way instead of 0, it will take care of that

**Comment by Raicuparta** [comment]
Closed by #74
